repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--settings-path", "pyproject.toml"]
  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: v3.0.0a5
  #   hooks:
  #     - id: pylint
  #       args: ["--rcfile=pyproject.toml"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length", "100"]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       args: ["--config-file", "pyproject.toml"]
